Repository bitfireAT/ical4android, pull requests merged in 2023-09, with the labels that each got.

#111 Updated AGP to 8.1.0 and Kotlin to 1.9.0
  build.gradle.kts
Labels: refactoring

#114 Ignore RDATEs when there's an also an infinite RRULE to avoid calendar provider exception
  lib/src/androidTest/kotlin/at/bitfire/ical4android/AndroidEventTest.kt
  lib/src/main/kotlin/at/bitfire/ical4android/AndroidEvent.kt
Labels: bug, 3rd party

#116 Update ical4j to `3.2.13`
  lib/build.gradle.kts
Labels: bug
