Repository bitfireAT/ical4android, pull requests merged in 2024-01, with the labels that each got.

#122 updated-jtx-board-version-source
  .github/workflows/test-dev.yml
Labels: enhancement, jtx board

#121 Updated contract, added method in JtxCollection + Test
  .github/workflows/test-dev.yml
  lib/src/androidTest/kotlin/at/bitfire/ical4android/JtxCollectionTest.kt
  lib/src/main/kotlin/at/bitfire/ical4android/JtxCollection.kt
  lib/src/main/kotlin/at/bitfire/ical4android/TaskProvider.kt
  lib/src/main/kotlin/at/techbee/jtx/JtxContract.kt
Labels: enhancement

#131 Fixed UID loading
  lib/src/androidTest/kotlin/at/bitfire/ical4android/AndroidEventTest.kt
  lib/src/main/kotlin/at/bitfire/ical4android/AndroidEvent.kt
Labels: bug
