Repository bitfireAT/ical4android, pull requests merged in 2024-11, with the labels that each got.

#185 `DateUtils.parseVTimeZone`: return null instead of throwing a RuntimeException
  lib/src/androidTest/kotlin/at/bitfire/ical4android/util/DateUtilsTest.kt
  lib/src/main/kotlin/at/bitfire/ical4android/util/DateUtils.kt
Labels: refactoring

#188 BatchOperation: set yield point after every 500 operations
  lib/src/androidTest/kotlin/at/bitfire/ical4android/DmfsStyleProvidersTaskTest.kt
  lib/src/androidTest/kotlin/at/bitfire/ical4android/DmfsTaskListTest.kt
  lib/src/androidTest/kotlin/at/bitfire/ical4android/DmfsTaskTest.kt
  lib/src/main/kotlin/at/bitfire/ical4android/BatchOperation.kt
  lib/src/main/kotlin/at/bitfire/ical4android/DmfsTask.kt
  lib/src/main/kotlin/at/bitfire/ical4android/DmfsTaskList.kt
Labels: bug

#191 Filter `RDATE` and `EXDATE` from exceptions
  lib/src/main/kotlin/at/bitfire/ical4android/validation/EventValidator.kt
  lib/src/test/kotlin/at/bitfire/ical4android/validation/EventValidatorTest.kt
Labels: enhancement
